name: vonMises
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - wheel
  - setuptools
  - scikit-build
  - requests
  - numpy
  - scipy
  - pandas
  - matplotlib
  - plotly
  - psutil
  - ruff
  - pytest
  - tqdm
